format_version: 10
environments:
  k8s:
    pipelines:
      - users
pipelines:
  users:
    group: mouse
    materials:
      users-git:
        git: git@scm.mouse.center:mouse/users.git
        auto_update: true
      framework-upstream:
        pipeline: framework
        stage: build
    stages:
      - build:
          jobs:
            test-and-build:
              elastic_profile_id: k8s
              tasks:
                - exec:
                    command: gradle
                    arguments:
                      - clean
                      - build
                      - test
                      - --fail-fast
                - exec:
                    command: gradle
                    arguments:
                      - push
            deploy:
              elastic_profile_id: kubectl
              tasks:
                - exec:
                    command: kubectl
                    arguments:
                      - rollout
                      - restart
                      - statefulset
                      - "-n"
                      - app
                      - users
